# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Earning')),
                ('date', models.DateField(verbose_name='Payment Date')),
                ('value', models.PositiveIntegerField(verbose_name='Earning Value in CHF')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', related_query_name='earning', to='project.Project')),
            ],
        ),
    ]
