# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='tasks', related_query_name='task', to='project.Resource'),
        ),
    ]
