# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_chance_issue_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Risk resolved'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'High'), (3, 'Very High')], verbose_name='Probability of the Risk'),
        ),
    ]
